import { site, releaseLabel } from '../data/site.mjs';
import { icon, tags, link, pageHeading, educationDetails, capabilities, escapeHtml } from '../components/layout.mjs';

function projectCard(project, base) {
  const ai = project.category === 'ai';
  return `<article class="project-card" data-category="${project.category}">
    <a class="project-visual ${ai ? 'visual-ai' : 'visual-web'}" href="${base}${project.path}" aria-label="查看${project.title}">
      ${ai ? `<div class="visual-caption"><span>KNOWLEDGE / INTELLIGENCE</span>${icon('sparkles')}</div><div class="knowledge-visual"><span class="document-node">${icon('files')}</span><span class="connection-line"></span><span class="core-node">${icon('brain-circuit')}</span><span class="connection-line"></span><span class="answer-node">${icon('message-square-text')}</span></div><div class="visual-bottom"><span>RAG + AGENT</span><span class="visual-status">V0.5 Agent · 本地可运行</span></div>` : `<div class="visual-caption"><span>DESIGN / DEVELOPMENT</span>${icon('code-2')}</div><img class="site-preview" src="${base}assets/site-preview.webp" alt="个人作品集 ${releaseLabel} 首页实际预览" width="1000" height="625" loading="lazy"><div class="visual-bottom"><span>PERSONAL PORTFOLIO</span><span>01 / ONGOING</span></div>`}
    </a>
    <div class="project-info"><div class="project-title-row"><span class="project-category">${ai ? 'AI 应用探索' : 'Web 开发实践'}</span><span class="project-state ${ai ? '' : 'is-live'}">${project.status}</span></div><a class="project-title" href="${base}${project.path}"><h3>${project.title}</h3>${icon('arrow-up-right')}</a><p>${project.description}</p>${tags(project.tags)}${project.source ? `<div class="project-source">${link(project.source, '查看源码', 'text-link', true)}</div>` : ''}</div>
  </article>`;
}

function noteRow(note, base) {
  const date = new Date(`${note.date}T00:00:00Z`);
  const month = new Intl.DateTimeFormat('en', { month: 'short', timeZone: 'UTC' }).format(date).toUpperCase();
  return `<article class="note-row" data-note data-date="${note.date}" data-search="${escapeHtml([note.title, note.description, note.category, ...note.tags].join(' '))}" data-category="${escapeHtml(note.category)}"><time class="note-date" datetime="${note.date}"><span>${note.date.slice(-2)}</span><span>${month} ${date.getUTCFullYear()}</span></time><div class="note-content"><div class="note-meta"><span>${escapeHtml(note.category)}</span><span>${note.reading}</span></div><h3><a href="${base}${note.path}">${escapeHtml(note.title)}</a></h3><p>${escapeHtml(note.description)}</p>${tags(note.tags)}</div><a class="round-link" href="${base}${note.path}" aria-label="阅读：${escapeHtml(note.title)}">${icon('arrow-up-right')}</a></article>`;
}

function projectStory(base) {
  const project = site.projects.find(item => item.id === 'knowledge-agent');
  return `<section class="section project-story" id="project-story"><div class="container"><div class="section-heading story-heading"><div><span class="eyebrow">PROJECT BREAKDOWN / 02</span><h2>把一个问题，拆成六个可验证的环节<span class="green-dot">.</span></h2><p>以本地知识库智能问答为例，记录从需求到工具调用的工程过程。</p></div>${link(`${base}${project.path}`, '查看完整项目')}</div><div class="story-intro"><article><span class="story-index">01</span><h3>项目介绍</h3><p>这是一个面向课程资料的本地知识库问答工具。用户上传 PDF 后，可以检索原文、查看页码依据，并让课程助手 Agent 根据问题选择检索或计算工具。</p><div class="story-actions">${link(project.demo, '打开本机 Demo', 'text-link')}${link(project.source, '查看 chatbot 仓库', 'text-link', true)}</div></article><article><span class="story-index">02</span><h3>技术栈</h3><div class="story-stack">${project.architecture.map(item => `<span>${item}</span>`).join('')}</div><p>Gradio 负责交互，pypdf 解析文档，RAG 提供带页码的检索上下文，Agent 负责工具规划，DeepSeek 负责模型回答。</p></article></div><div class="story-timeline"><div class="story-section-label"><span class="story-index">03</span><h3>迭代过程</h3></div><ol><li><strong>V0.3</strong><span>PDF 资料问答：完成文档解析、分块检索与页码引用。</span></li><li><strong>V0.4</strong><span>提示工程模板：加入题目解析卡与学习计划卡。</span></li><li><strong>V0.5</strong><span>课程助手 Agent：组合 PDF 检索与安全计算器工具。</span></li></ol></div><div class="story-columns"><article><span class="story-index">04</span><h3>核心亮点</h3><ul>${['回答附带原文页码，便于回到资料核对', 'Agent 根据问题选择 PDF 检索或计算器', '没有模型密钥时仍可运行本地工具', '通过环境变量隔离新模型密钥'].map(item => `<li>${icon('check')}${item}</li>`).join('')}</ul></article><article><span class="story-index">05</span><h3>解决问题</h3><ul>${['减少课程 PDF 中反复翻页和人工定位的时间', '避免让大模型直接承担可验证的算术计算', '让不同问答模式拥有稳定的结构化输出', '在模型不可用时保留可验收的本地能力'].map(item => `<li>${icon('check')}${item}</li>`).join('')}</ul></article></div><article class="story-thinking"><span class="story-index">06</span><div><h3>工程思路</h3><p>先把资料解析、检索、计算拆成可以独立测试的工具，再让 Agent 负责组合它们。每次迭代都保留真实输入、页码引用和失败状态，先验证结果可追溯，再接入模型生成。</p></div></article></div></section>`;
}

export function home(base) {
  return `<section class="hero" aria-labelledby="hero-title"><picture><source media="(max-width: 760px)" srcset="${base}assets/workspace-mobile.webp"><img class="hero-image" src="${base}assets/workspace.webp" srcset="${base}assets/workspace-1280.webp 1280w, ${base}assets/workspace.webp 1920w" sizes="100vw" alt="笔记本电脑上的代码编辑器与开发工作台" width="1920" height="1280" fetchpriority="high"></picture><div class="hero-shade"></div><div class="container hero-content"><div class="hero-eyebrow"><span class="status-dot"></span>HELLO WORLD, I'M</div><h1 id="hero-title">${site.name}<span>.</span></h1><p class="hero-statement">连接代码，探索自动化。</p><p class="hero-description">${site.education.institution}<br>${site.education.level} · ${site.education.major}<br>${site.education.graduation}</p><div class="hero-actions">${link(`${base}projects/index.html`, '探索我的项目', 'button button-lime')}${link(`${base}about/index.html`, '更多关于我', 'hero-about')}</div><div class="hero-foot"><span>DEVELOPER · BUILDER · LEARNER</span><a href="#selected-work">向下探索 ${icon('arrow-down')}</a></div></div></section>
    <div class="focus-strip"><div class="container focus-inner"><span class="focus-label">正在关注 <span class="short-line"></span></span>${site.studyAreas.map(area => `<span>${icon(area.icon)}${area.title}</span>`).join('')}<span>${icon('book-open')}学习与记录</span><span class="focus-ending">STAY CURIOUS. KEEP BUILDING.</span></div></div>
    <section class="section container" id="selected-work"><div class="section-heading"><div><span class="eyebrow">SELECTED WORK / 01</span><h2>想法落地的地方<span class="green-dot">.</span></h2><p>在项目中学习，在实践中找到答案。</p></div>${link(`${base}projects/index.html`, '全部项目')}</div><div class="project-grid">${site.projects.map(project => projectCard(project, base)).join('')}</div></section>
    ${projectStory(base)}
    <section class="about-band"><div class="container about-inner"><div><span class="eyebrow">A LITTLE ABOUT ME / 03</span><h2>不止于写代码，<br>也关心问题本身。</h2></div><div class="about-copy"><p>你好，我是 ${site.name}，就读于${site.education.institution}，${site.education.major}专业，${site.education.level}，${site.education.graduation}。</p><p>我主学${site.studyAreas.map(area => area.title).join('、')}，也在探索 AI 应用与 Web 开发。在这里记录学习过程与项目实践。</p>${link(`${base}about/index.html`, '认识我')}</div></div></section>
    <section class="section container"><div class="section-heading"><div><span class="eyebrow">NOTES & THOUGHTS / 04</span><h2>边学，边记录<span class="green-dot">.</span></h2><p>把实践中的思考，写成下一次出发的起点。</p></div>${link(`${base}notes/index.html`, '全部笔记')}</div>${site.notes.map(note => noteRow(note, base)).join('')}</section>
    <section class="contact-band"><div class="container contact-inner"><div><span class="eyebrow">LET'S CONNECT</span><h2>让下一个想法，从交流开始。</h2></div>${link(site.github, '访问我的 GitHub', 'button button-dark', true)}</div></section>`;
}

export function about(base) {
  return `<div class="container">${pageHeading('ABOUT ME / 01', '关于我', '保持好奇，认真构建，让每一次实践成为积累。')}<section class="profile-section"><div class="profile-mark" aria-label="${site.name} 个人标识">${site.name}<span>_</span><span class="profile-coordinate">EXPLORE. BUILD. REPEAT.</span></div><div class="profile-copy"><span class="eyebrow">HELLO, I'M ${site.name}</span><h2>把好奇心，变成行动。</h2><p>我是 ${site.name}，就读于${site.education.institution}，${site.education.major}专业，${site.education.level}，${site.education.graduation}。</p><p>目前主学${site.studyAreas.map(area => area.title).join('、')}。我也在探索 AI 应用与 Web 开发，用项目和笔记记录学习过程。</p>${link(site.github, site.handle, 'text-link', true)}</div></section><section class="section"><div class="section-heading"><div><span class="eyebrow">CURRENT STUDIES</span><h2>主学方向</h2></div><span class="muted">持续学习，逐步深入</span></div><div class="direction-grid">${site.studyAreas.map((area, index) => `<article>${icon(area.icon)}<span class="direction-number">0${index + 1}</span><h3>${area.title}</h3><p>${area.description}</p></article>`).join('')}</div></section><section class="detail-line"><div><span class="eyebrow">EDUCATION</span><h2>教育经历</h2></div><div class="pending-inline">${icon('graduation-cap')}${educationDetails()}</div></section><section class="detail-line"><div><span class="eyebrow">NEXT CHAPTER</span><h2>继续了解</h2></div><div class="inline-actions">${link(`${base}projects/index.html`, '项目作品', 'button button-dark')}${link(`${base}resume/index.html`, '个人简历', 'button button-outline')}</div></section></div>`;
}

export function projects(base) {
  return `<div class="container">${pageHeading('PROJECTS / 02', '项目作品', '把想法变成可以看见、可以使用的作品。')}<div class="list-toolbar"><div class="filter-tabs" role="group" aria-label="项目分类"><button class="active" data-project-filter="all" aria-pressed="true">全部项目 <span>2</span></button><button data-project-filter="ai" aria-pressed="false">AI 应用 <span>1</span></button><button data-project-filter="web" aria-pressed="false">Web 开发 <span>1</span></button></div><span class="muted result-count" aria-live="polite">2 个项目</span></div><div class="project-grid projects-page">${site.projects.map(project => projectCard(project, base)).join('')}</div><div class="end-note"><span class="status-dot"></span>新的想法，正在路上。</div></div>`;
}

export function notes(base) {
  const categories = [...new Set(site.notes.map(note => note.category))];
  return `<div class="container notes-page">${pageHeading('NOTES & THOUGHTS / 03', '技术笔记', '记录解决问题的过程，也记录那些值得再次思考的问题。')}
    <div class="list-toolbar notes-toolbar" data-enhanced><div class="filter-tabs" role="group" aria-label="笔记分类"><button class="active" data-note-filter="all" aria-pressed="true">全部笔记</button>${categories.map(category => `<button data-note-filter="${escapeHtml(category)}" aria-pressed="false">${escapeHtml(category)}</button>`).join('')}</div>
    <div class="notes-tools"><div class="search-field">${icon('search')}<input type="search" placeholder="搜索笔记..." aria-label="搜索技术笔记" maxlength="100"><button class="icon-button clear-search" type="button" aria-label="清空搜索" title="清空搜索" disabled>${icon('x')}</button></div><select id="note-sort" aria-label="笔记排序"><option value="newest">最新发布</option><option value="oldest">最早发布</option></select></div></div>
    <p class="notes-count muted" role="status">共 ${site.notes.length} 篇笔记</p><div class="notes-list">${site.notes.map(note => noteRow(note, base)).join('')}</div><div class="empty-state" id="notes-empty" hidden>${icon('search')}<h2>暂时没有找到笔记</h2><button class="button button-outline" id="reset-search">${icon('rotate-ccw')}重置筛选</button></div></div>`;
}

export function resume(base) {
  return `<div class="container resume-page">${pageHeading('RESUME / 04', '个人简历', '将学习、实践与成长，整理成一份清晰的履历。')}<section class="resume-layout"><div class="resume-sheet"><div class="resume-sheet-top"><div><span class="eyebrow">CURRICULUM VITAE</span><h2>${site.name}<span class="green-dot">.</span></h2><span>${site.handle}</span></div>${icon('file-user')}</div><div class="resume-summary"><h3>主学方向</h3>${tags(site.studyAreas.map(area => area.title))}</div><div class="resume-summary"><h3>项目实践</h3><a href="${base}projects/personal-site/index.html">个人技术作品集 ${icon('arrow-up-right')}</a></div><div class="resume-summary"><h3>教育背景</h3>${educationDetails()}</div><div class="resume-draft">个人资料预览 · 非正式简历</div></div><aside class="resume-sidebar"><span class="eyebrow">DOCUMENT STATUS</span><h2>简历待上传</h2><p>正式 PDF 简历尚未提供。个人资料完善后，将在这里提供预览与下载。</p><button class="button button-disabled" disabled>${icon('download')}暂无可下载文件</button><div class="resume-other"><span class="eyebrow">IN THE MEANTIME</span>${link(`${base}projects/index.html`, '先看看项目作品')}${link(site.github, '访问 GitHub', 'text-link', true)}</div></aside></section></div>`;
}

export function projectDetail(base, id) {
  const project = site.projects.find(item => item.id === id);
  const ai = project.category === 'ai';
  const projectBody = ai ? `<section class="article-section"><h2>项目能力</h2><p>${project.description}</p><p>当前项目来自 chatbot V0.5，具备多轮对话、PDF 资料检索、结构化提示模板、课程助手 Agent 与安全计算器工具。</p>${capabilities(project.capabilities)}</section><section class="article-section"><h2>接入方式</h2><div class="demo-panel"><div><h3>${project.integration.label}</h3><p>${project.integration.note}</p></div>${link(project.demo, '打开本机 Demo', 'button button-dark')}</div></section><section class="article-section"><h2>技术结构</h2><div class="architecture-flow">${[['files', 'PDF 文档'], ['search', 'RAG 检索'], ['brain-circuit', 'Agent 规划'], ['calculator', '安全计算器']].map(([symbol, label], index) => `<div>${icon(symbol)}<span>${label}</span></div>${index < 3 ? icon('arrow-right', 'architecture-arrow') : ''}`).join('')}</div></section><section class="article-section"><h2>真实版本</h2><ul class="check-list">${['V0.3 PDF 资料问答', 'V0.4 题目解析卡与学习计划卡', 'V0.5 课程助手 Agent：PDF 检索 + 计算器', '本地测试通过；模型密钥由环境变量提供'].map(item => `<li>${icon('check')}${item}</li>`).join('')}</ul></section>` : `<section class="article-section"><h2>项目概览</h2><p>${project.description}</p><p>当前版本已建立首页、关于我、项目作品、技术笔记与个人简历五个主要页面，并接入统一导航、响应式布局和静态构建流程。</p></section><section class="article-section"><h2>技术结构</h2><div class="architecture-flow">${[['file-code', '页面与内容'], ['blocks', '共享组件'], ['terminal', '静态构建'], ['globe', '持续部署']].map(([symbol, label], index) => `<div>${icon(symbol)}<span>${label}</span></div>${index < 3 ? icon('arrow-right', 'architecture-arrow') : ''}`).join('')}</div></section>`;
  return `<article class="container article-page"><a class="back-link" href="${base}projects/index.html">${icon('arrow-left')}全部项目</a>${pageHeading(ai ? 'AI APPLICATION / PROJECT' : 'WEB DEVELOPMENT / PROJECT', project.title, project.subtitle)}<div class="article-meta">${tags(project.tags)}<span class="project-state ${ai ? '' : 'is-live'}">${project.status}</span></div>${projectBody}${!ai ? `<section class="article-section" id="version-history"><h2>版本记录</h2><h3>V0.5 · 正式发布与全量回归</h3><p>完成全站页面、链接、适配、资源、部署配置和异常路径回归；统一公开仓库入口、版本文案和安全响应头，保留真实的简历待上传状态。</p><h3>V0.4.1 · 公开仓库入口</h3><p>确认 personal-site 与 chatbot 仓库已公开，在项目卡片和详情页提供源码入口，更新仓库访问状态。</p><h3>V0.4 · 功能完善与交互优化</h3><p>完善笔记筛选、排序与文章目录，增加轻量动效和响应式图片，优化移动端导航、404 恢复与资源异常状态。</p><h3>V0.3 · chatbot 项目接入</h3><p>接入真实 chatbot V0.5 的 PDF 资料问答、课程助手 Agent 和安全计算器，增加本机 Demo 入口；首页补齐项目介绍、技术栈、迭代过程、核心亮点、解决问题与工程思路。</p><h3>V0.2.1 · 院校与学习方向</h3><p>补充昆明理工大学津桥学院、预计 2027 年毕业，以及嵌入式开发、C 语言、PLC 自动化技术三个主学方向。</p><h3>V0.2 · 个人资料完善</h3><p>补充本科学历与电气工程及其自动化专业，更新首页、关于我和简历页。统一当前版本标识，继续进行本地验收。</p><h3>V0.1 · 基础架构</h3><p>建立五个核心页面、项目与笔记入口，完成响应式布局、测试及部署配置。</p>${link(`${base}notes/building-v0-1/index.html`, '阅读 V0.1 开发笔记')}</section>` : ''}<div class="project-links">${!ai ? link(`${base}index.html`, '预览网站', 'button button-dark') : ''}${link(project.source, '查看项目仓库', 'button button-outline', true)}<span class="muted">公开源码仓库</span></div></article>`;
}

export function article(base, slug) {
  const note = site.notes.find(item => item.slug === slug);
  const related = site.notes.filter(item => item.slug !== slug).slice(0, 2);
  return `<div class="reading-progress" data-enhanced><progress max="100" value="0" aria-label="阅读进度"></progress></div><div class="container note-article"><a class="back-link" href="${base}notes/index.html">${icon('arrow-left')}全部笔记</a>
    <header class="article-header"><span class="eyebrow">${escapeHtml(note.category)} · <time datetime="${note.date}">${note.date.replaceAll('-', '.')}</time> · ${note.reading}</span><h1>${escapeHtml(note.title)}</h1><p>${escapeHtml(note.description)}</p>${tags(note.tags)}</header>
    <div class="reading-layout"><aside class="article-sidebar"><nav class="article-toc" aria-label="文章目录"><span class="eyebrow">文章目录</span><ol>${note.sections.map(section => `<li><a href="#${section.id}">${escapeHtml(section.title)}</a></li>`).join('')}</ol></nav></aside>
    <article class="prose" data-reading-body>${note.sections.map(section => `<section class="article-section" id="${section.id}"><h2 tabindex="-1">${escapeHtml(section.title)}</h2>${section.paragraphs.map(text => `<p>${escapeHtml(text)}</p>`).join('')}${section.code ? `<pre><code>${escapeHtml(section.code)}</code></pre>` : ''}</section>`).join('')}<div class="article-end">${icon('check')}记录于 ${escapeHtml(note.release)}</div></article></div>
    <section class="related-notes"><h2>继续阅读</h2>${related.map(item => noteRow(item, base)).join('')}</section></div>`;
}

export function notFound(base) {
  return `<section class="container not-found"><span class="error-code">404<span class="green-dot">.</span></span><h1>页面未找到</h1><p>页面可能已移动，或地址输入有误。</p><div class="recovery-actions">${link(`${base}index.html`, '回到首页', 'button button-dark')}${link(`${base}projects/index.html`, '项目作品', 'button button-outline')}${link(`${base}notes/index.html`, '技术笔记', 'text-link')}</div></section>`;
}
