import { site, releaseLabel } from '../data/site.mjs';
import { icon, tags, link, pageHeading, educationDetails } from '../components/layout.mjs';

function projectCard(project, base) {
  const ai = project.category === 'ai';
  return `<article class="project-card" data-category="${project.category}">
    <a class="project-visual ${ai ? 'visual-ai' : 'visual-web'}" href="${base}${project.path}" aria-label="查看${project.title}">
      ${ai ? `<div class="visual-caption"><span>KNOWLEDGE / INTELLIGENCE</span>${icon('sparkles')}</div><div class="knowledge-visual"><span class="document-node">${icon('files')}</span><span class="connection-line"></span><span class="core-node">${icon('brain-circuit')}</span><span class="connection-line"></span><span class="answer-node">${icon('message-square-text')}</span></div><div class="visual-bottom"><span>RAG + AGENT</span><span class="visual-status">项目展示筹备中</span></div>` : `<div class="visual-caption"><span>DESIGN / DEVELOPMENT</span>${icon('code-2')}</div><img class="site-preview" src="${base}assets/site-preview.webp" alt="个人作品集 ${releaseLabel} 首页实际预览" width="1000" height="625" loading="lazy"><div class="visual-bottom"><span>PERSONAL PORTFOLIO</span><span>01 / ONGOING</span></div>`}
    </a>
    <div class="project-info"><div class="project-title-row"><span class="project-category">${ai ? 'AI 应用探索' : 'Web 开发实践'}</span><span class="project-state ${ai ? '' : 'is-live'}">${project.status}</span></div><a class="project-title" href="${base}${project.path}"><h3>${project.title}</h3>${icon('arrow-up-right')}</a><p>${project.description}</p>${tags(project.tags)}</div>
  </article>`;
}

function noteRow(note, base) {
  return `<article class="note-row" data-note data-search="${note.title} ${note.description} ${note.category}" data-category="${note.category}"><div class="note-date"><span>08</span><span>SEP 2026</span></div><div class="note-content"><div class="note-meta"><span>${note.category}</span><span>${note.reading}</span></div><h3><a href="${base}${note.path}">${note.title}</a></h3><p>${note.description}</p></div><a class="round-link" href="${base}${note.path}" aria-label="阅读：${note.title}">${icon('arrow-up-right')}</a></article>`;
}

export function home(base) {
  return `<section class="hero" aria-labelledby="hero-title"><img class="hero-image" src="${base}assets/workspace.webp" alt="笔记本电脑上的代码编辑器与开发工作台" width="1920" height="1280" fetchpriority="high"><div class="hero-shade"></div><div class="container hero-content"><div class="hero-eyebrow"><span class="status-dot"></span>HELLO WORLD, I'M</div><h1 id="hero-title">${site.name}<span>.</span></h1><p class="hero-statement">探索 AI，构建真实应用。</p><p class="hero-description">${site.education.level} · ${site.education.major}<br>记录代码、学习，以及从想法到实现的每一步。</p><div class="hero-actions">${link(`${base}projects/index.html`, '探索我的项目', 'button button-lime')}${link(`${base}about/index.html`, '更多关于我', 'hero-about')}</div><div class="hero-foot"><span>DEVELOPER · BUILDER · LEARNER</span><a href="#selected-work">向下探索 ${icon('arrow-down')}</a></div></div></section>
    <div class="focus-strip"><div class="container focus-inner"><span class="focus-label">正在关注 <span class="short-line"></span></span><span>${icon('brain-circuit')}人工智能应用</span><span>${icon('blocks')}RAG & Agent</span><span>${icon('code-2')}Web 开发</span><span>${icon('book-open')}学习与记录</span><span class="focus-ending">STAY CURIOUS. KEEP BUILDING.</span></div></div>
    <section class="section container" id="selected-work"><div class="section-heading"><div><span class="eyebrow">SELECTED WORK / 01</span><h2>想法落地的地方<span class="green-dot">.</span></h2><p>在项目中学习，在实践中找到答案。</p></div>${link(`${base}projects/index.html`, '全部项目')}</div><div class="project-grid">${site.projects.map(project => projectCard(project, base)).join('')}</div></section>
    <section class="about-band"><div class="container about-inner"><div><span class="eyebrow">A LITTLE ABOUT ME / 02</span><h2>不止于写代码，<br>也关心问题本身。</h2></div><div class="about-copy"><p>你好，我是 ${site.name}，${site.education.level}学历，${site.education.major}专业。这里记录我在 Web 开发与 AI 应用中的学习和实践。</p><p>我希望让每一次实践都有迹可循，也让每一个作品都能清楚地表达它解决了什么问题。</p>${link(`${base}about/index.html`, '认识我')}</div></div></section>
    <section class="section container"><div class="section-heading"><div><span class="eyebrow">NOTES & THOUGHTS / 03</span><h2>边学，边记录<span class="green-dot">.</span></h2><p>把实践中的思考，写成下一次出发的起点。</p></div>${link(`${base}notes/index.html`, '全部笔记')}</div>${site.notes.map(note => noteRow(note, base)).join('')}</section>
    <section class="contact-band"><div class="container contact-inner"><div><span class="eyebrow">LET'S CONNECT</span><h2>让下一个想法，从交流开始。</h2></div>${link(site.github, '访问我的 GitHub', 'button button-dark', true)}</div></section>`;
}

export function about(base) {
  return `<div class="container">${pageHeading('ABOUT ME / 01', '关于我', '保持好奇，认真构建，让每一次实践成为积累。')}<section class="profile-section"><div class="profile-mark" aria-label="${site.name} 个人标识">${site.name}<span>_</span><span class="profile-coordinate">EXPLORE. BUILD. REPEAT.</span></div><div class="profile-copy"><span class="eyebrow">HELLO, I'M ${site.name}</span><h2>把好奇心，变成行动。</h2><p>我是 ${site.name}，${site.education.level}学历，${site.education.major}专业。我正在围绕 AI 应用与 Web 开发展开学习与实践，并用项目和笔记记录过程。</p><p>我关注从问题到实现的完整路径：如何组织知识、连接工具，以及把技术能力转化为可以使用的产品。</p>${link(site.github, site.handle, 'text-link', true)}</div></section><section class="section"><div class="section-heading"><div><span class="eyebrow">AREAS OF INTEREST</span><h2>关注的技术方向</h2></div><span class="muted">持续学习，逐步深入</span></div><div class="direction-grid"><article>${icon('brain-circuit')}<span class="direction-number">01</span><h3>AI 应用</h3><p>探索大语言模型、知识库检索与智能体工具调用。</p>${tags(['Python', 'RAG', 'Agent', 'Gradio'])}</article><article>${icon('code-2')}<span class="direction-number">02</span><h3>Web 开发</h3><p>从页面结构、响应式布局，到流畅清晰的交互。</p>${tags(['HTML', 'CSS', 'JavaScript'])}</article><article>${icon('git-branch')}<span class="direction-number">03</span><h3>工程实践</h3><p>通过版本管理、测试与文档，让迭代有据可循。</p>${tags(['Git', 'GitHub Actions', 'Node.js'])}</article></div></section><section class="detail-line"><div><span class="eyebrow">EDUCATION</span><h2>教育经历</h2></div><div class="pending-inline">${icon('graduation-cap')}${educationDetails()}</div></section><section class="detail-line"><div><span class="eyebrow">NEXT CHAPTER</span><h2>继续了解</h2></div><div class="inline-actions">${link(`${base}projects/index.html`, '项目作品', 'button button-dark')}${link(`${base}resume/index.html`, '个人简历', 'button button-outline')}</div></section></div>`;
}

export function projects(base) {
  return `<div class="container">${pageHeading('PROJECTS / 02', '项目作品', '把想法变成可以看见、可以使用的作品。')}<div class="list-toolbar"><div class="filter-tabs" role="group" aria-label="项目分类"><button class="active" data-project-filter="all" aria-pressed="true">全部项目 <span>2</span></button><button data-project-filter="ai" aria-pressed="false">AI 应用 <span>1</span></button><button data-project-filter="web" aria-pressed="false">Web 开发 <span>1</span></button></div><span class="muted result-count" aria-live="polite">2 个项目</span></div><div class="project-grid projects-page">${site.projects.map(project => projectCard(project, base)).join('')}</div><div class="end-note"><span class="status-dot"></span>新的想法，正在路上。</div></div>`;
}

export function notes(base) {
  return `<div class="container notes-page">${pageHeading('NOTES & THOUGHTS / 03', '技术笔记', '记录解决问题的过程，也记录那些值得再次思考的问题。')}<div class="list-toolbar"><div class="filter-tabs" role="group" aria-label="笔记分类"><button class="active" data-note-filter="all" aria-pressed="true">全部笔记</button><button data-note-filter="工程实践" aria-pressed="false">工程实践</button><button data-note-filter="AI 应用" aria-pressed="false">AI 应用</button></div><label class="search-field">${icon('search')}<input type="search" placeholder="搜索笔记..." aria-label="搜索技术笔记" maxlength="100"></label></div><div class="notes-list">${site.notes.map(note => noteRow(note, base)).join('')}</div><p class="notes-count muted" aria-live="polite">共 1 篇笔记</p><div class="empty-state" id="notes-empty" hidden>${icon('search')}<h2>暂时没有找到笔记</h2><button class="button button-outline" id="reset-search">重置筛选 ${icon('rotate-ccw')}</button></div></div>`;
}

export function resume(base) {
  return `<div class="container resume-page">${pageHeading('RESUME / 04', '个人简历', '将学习、实践与成长，整理成一份清晰的履历。')}<section class="resume-layout"><div class="resume-sheet"><div class="resume-sheet-top"><div><span class="eyebrow">CURRICULUM VITAE</span><h2>${site.name}<span class="green-dot">.</span></h2><span>${site.handle}</span></div>${icon('file-user')}</div><div class="resume-summary"><h3>关注方向</h3><p>AI 应用 / Web 开发 / 工程实践</p></div><div class="resume-summary"><h3>项目实践</h3><a href="${base}projects/personal-site/index.html">个人技术作品集 ${icon('arrow-up-right')}</a></div><div class="resume-summary"><h3>教育背景</h3>${educationDetails()}</div><div class="resume-draft">个人资料预览 · 非正式简历</div></div><aside class="resume-sidebar"><span class="eyebrow">DOCUMENT STATUS</span><h2>简历待上传</h2><p>正式 PDF 简历尚未提供。个人资料完善后，将在这里提供预览与下载。</p><button class="button button-disabled" disabled>${icon('download')}暂无可下载文件</button><div class="resume-other"><span class="eyebrow">IN THE MEANTIME</span>${link(`${base}projects/index.html`, '先看看项目作品')}${link(site.github, '访问 GitHub', 'text-link', true)}</div></aside></section></div>`;
}

export function projectDetail(base, id) {
  const project = site.projects.find(item => item.id === id);
  const ai = project.category === 'ai';
  return `<article class="container article-page"><a class="back-link" href="${base}projects/index.html">${icon('arrow-left')}全部项目</a>${pageHeading(ai ? 'AI APPLICATION / PROJECT' : 'WEB DEVELOPMENT / PROJECT', project.title, project.subtitle)}<div class="article-meta">${tags(project.tags)}<span class="project-state ${ai ? '' : 'is-live'}">${project.status}</span></div><section class="article-section"><h2>项目概览</h2><p>${project.description}</p>${ai ? '<p>本页为项目展示框架。项目实现细节、运行截图、源码地址与在线 Demo 尚未录入，以下为后续展示方向。</p>' : '<p>当前版本已建立首页、关于我、项目作品、技术笔记与个人简历五个主要页面，并接入统一导航、响应式布局和静态构建流程。</p>'}</section><section class="article-section"><h2>${ai ? '规划架构' : '技术结构'}</h2><div class="architecture-flow">${(ai ? [['files', '本地文档'], ['search', 'RAG 检索'], ['brain-circuit', 'Agent / LLM'], ['message-square-text', 'Gradio 问答']] : [['file-code', '页面与内容'], ['blocks', '共享组件'], ['terminal', '静态构建'], ['globe', '持续部署']]).map(([symbol, label], index) => `<div>${icon(symbol)}<span>${label}</span></div>${index < 3 ? icon('arrow-right', 'architecture-arrow') : ''}`).join('')}</div></section><section class="article-section"><h2>${ai ? '待补充资料' : `${releaseLabel} 已完成`}</h2><ul class="check-list">${(ai ? ['项目介绍与真实功能清单', '运行截图与架构实现说明', '经过验证的 GitHub 源码和在线 Demo 地址'] : ['五个核心页面与统一导航、页脚', '本科及电气工程及其自动化专业资料展示', '移动端适配、项目分类与笔记搜索', '构建校验、版本文档与自动部署配置']).map(item => `<li>${icon(ai ? 'circle-dashed' : 'check')}${item}</li>`).join('')}</ul></section>${!ai ? `<section class="article-section" id="version-history"><h2>版本记录</h2><h3>V0.2 · 个人资料完善</h3><p>补充本科学历与电气工程及其自动化专业，更新首页、关于我和简历页。统一当前版本标识，继续进行本地验收。</p><h3>V0.1 · 基础架构</h3><p>建立五个核心页面、项目与笔记入口，完成响应式布局、测试及部署配置。</p>${link(`${base}notes/building-v0-1/index.html`, '阅读 V0.1 开发笔记')}</section>` : ''}<div class="project-links">${!ai ? link(`${base}index.html`, '预览网站', 'button button-dark') : '<button class="button button-disabled" disabled>Demo 待接入</button>'}<span class="muted">${ai ? '源码地址待提供' : '源码仓库暂未公开'}</span></div></article>`;
}

export function article(base) {
  return `<article class="container article-page prose"><a class="back-link" href="${base}notes/index.html">${icon('arrow-left')}全部笔记</a><header class="article-header"><span class="eyebrow">工程实践 · 2026.09.08 · 3 分钟</span><h1>从零开始，搭建个人作品集的第一步</h1><p>先建立清晰的结构，再让内容与作品持续生长。</p></header><section class="article-section"><h2>先确定第一版要解决的问题</h2><p>个人作品集承载的不只是项目列表，也包括个人介绍、技术笔记和履历。V0.1 首先建立这几类内容的入口，让后续更新有明确的位置。</p><p>第一版的范围是基础架构。对于尚未提供的教育信息、PDF 简历及 AI 项目演示地址，页面明确保留待补充状态。</p><h2>选择静态多页面结构</h2><p>这个版本使用 HTML、CSS、JavaScript 与 Node.js 原生模块。构建时，共享布局和内容数据被生成为独立的 HTML 页面。导航和正文不依赖客户端 JavaScript，页面可直接访问，也便于搜索引擎读取。</p><pre><code>src/
  components/   共享布局与组件
  data/         个人资料和内容
  pages/        页面模板
  styles/       全局样式
scripts/        构建与本地服务
tests/          自动化校验
docs/           版本与测试记录</code></pre><h2>给后续迭代留下空间</h2><p>项目内容与页面布局分开维护；项目分类和笔记搜索采用渐进增强。即使脚本不可用，项目和文章仍能正常阅读。</p><p>部署产物是独立的静态文件，路径兼容 GitHub Pages 的仓库子目录。GitHub Actions 负责构建、校验和发布，Vercel 则通过相同构建命令输出站点。</p><h2>把交付过程也当作作品的一部分</h2><p>代码之外，同步记录版本范围、环境、测试结果和已知限制。每次正式迭代通过 Git 提交和标签保存，以便回看一次改变为什么发生、完成了什么。</p><p>下一步是补齐真实个人资料与项目素材，让这个技术空间逐步拥有更完整的内容。</p></section><div class="article-end">${icon('check')}记录于 V0.1 基础架构版本</div></article>`;
}

export function notFound(base) {
  return `<section class="container not-found"><span class="error-code">404<span class="green-dot">.</span></span><h1>这一页，还没有故事。</h1><p>页面可能已移动，或地址输入有误。</p>${link(`${base}index.html`, '回到首页', 'button button-dark')}</section>`;
}
